########################################################################
########################################################################
#### 
#### Server Info 
server:
  port: 18080
spring.data.rest.base-path: /api
####
#### Server Info 
########################################################################
########################################################################


########################################################################
########################################################################
#### 
#### Spring Setting 
spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp 
####
#### Spring JPA
########################################################################
########################################################################